version: '3.8'
services:
  app:
    # build: .
    image: node:14.8.0
    working_dir: /usr/src/app
    environment:
      - API_PORT=4004
      - DEBUG_PORT=9449
    # command: npm run ${NPM_RUN_COMMAND:-start}
    ports:
      - 4004:4004
      - 9449:9449
    volumes:
      - .:/usr/src/app:cached
    # depends_on:
    #   - database
  # database:
  #   image: mongo:3.6.18-xenial
  #   expose:
  #     - 27017
  #   volumes:
  #     - mongodata:/data/db
#   mongodata: